package generator

import (
	"fmt"
	"strings"

	"github.com/ajmasia/shellify/internal/domain"
)

// TmuxGenerator generates bash scripts for tmux sessions.
type TmuxGenerator struct{}

func (g *TmuxGenerator) Name() string {
	return "tmux"
}

func (g *TmuxGenerator) FileExtension() string {
	return ".sh"
}

type paneMapping struct {
	pane       *domain.Pane
	paneOffset int
}

type windowPanesResult struct {
	splitLines   []string
	leafMappings []paneMapping
}

func getFirstLeaf(pane *domain.Pane) *domain.Pane {
	if len(pane.Children) == 0 {
		return pane
	}
	return getFirstLeaf(&pane.Children[0])
}

func (g *TmuxGenerator) resolvePaneDir(pane *domain.Pane) string {
	if pane == nil || pane.WorkingDirectory == "" {
		return "$WORKING_DIR"
	}
	dir := pane.WorkingDirectory
	if strings.HasPrefix(dir, "~/") {
		return "$HOME" + dir[1:]
	}
	if dir == "~" {
		return "$HOME"
	}
	if !isAbsolutePath(dir) {
		return "$WORKING_DIR/" + dir
	}
	return dir
}

func buildInlineCommand(cmd string) string {
	if cmd == "" {
		return ""
	}
	// Single quotes must use '\'' (exit-single-quote, escaped-quote, re-enter-single-quote)
	// because inside the outer double-quoted shell string, \' is not a valid escape for '.
	// Double quotes must be escaped as \" to avoid ending the outer double-quoted string.
	// $SHELL is expanded at script runtime so aliases and functions from the user's rc file
	// are available via the -i (interactive) flag.
	escaped := strings.ReplaceAll(cmd, `'`, `'\''`)
	escaped = strings.ReplaceAll(escaped, `"`, `\"`)
	return fmt.Sprintf(`"$SHELL -i -c '%s; exec $SHELL'"`, escaped)
}

func (g *TmuxGenerator) Generate(session domain.Session) (string, error) {
	sessionDir := session.WorkingDirectory
	if sessionDir == "" {
		sessionDir = "$HOME"
	} else if strings.HasPrefix(sessionDir, "~/") {
		sessionDir = "$HOME" + sessionDir[1:]
	} else if sessionDir == "~" {
		sessionDir = "$HOME"
	}

	lines := []string{
		"#!/bin/bash",
		fmt.Sprintf("# Session: %s", session.SessionName),
		"# Generated by Shellify",
		fmt.Sprintf("# Usage: chmod +x %s.sh && ./%s.sh", session.SessionName, session.SessionName),
		"set -e",
		"",
		"# Working directory for the session",
		fmt.Sprintf(`WORKING_DIR="%s"`, sessionDir),
		"",
		"# Detect terminal size (works inside and outside tmux)",
		`if [ -n "$TMUX" ]; then`,
		`    TERM_COLS=$(tmux display-message -p "#{client_width}")`,
		`    TERM_LINES=$(tmux display-message -p "#{client_height}")`,
		"else",
		"    TERM_COLS=$(tput cols)",
		"    TERM_LINES=$(tput lines)",
		"fi",
		"",
		"# Detect pane-base-index from tmux config",
		`PANE_BASE=$(tmux start-server \; show-options -gv pane-base-index 2>/dev/null || echo "0")`,
		"",
	}

	// Kill existing session — use exact name match to avoid tmux prefix matching
	lines = append(lines, "# Kill existing session if it exists (exact name match)")
	lines = append(lines, fmt.Sprintf(
		`tmux list-sessions -F "#{session_name}" 2>/dev/null | grep -qxF "%s" && tmux kill-session -t "%s" || true`,
		session.SessionName, session.SessionName,
	))
	lines = append(lines, "")

	// Environment variables
	if len(session.Environment) > 0 {
		lines = append(lines, "# Environment variables")
		for key, value := range session.Environment {
			lines = append(lines, fmt.Sprintf(`export %s="%s"`, key, value))
		}
		lines = append(lines, "")
	}

	// Pre-commands
	if len(session.PreCommands) > 0 {
		lines = append(lines, "# Pre-session commands")
		lines = append(lines, session.PreCommands...)
		lines = append(lines, "")
	}

	if len(session.Windows) == 0 {
		lines = append(lines, `echo "No windows defined"`)
		lines = append(lines, "exit 1")
		return strings.Join(lines, "\n"), nil
	}

	firstWindow := &session.Windows[0]

	// Resolve first leaf pane for new-session
	firstPaneDir := "$WORKING_DIR"
	firstPaneCmd := ""
	if len(firstWindow.Panes) > 0 {
		firstLeaf := getFirstLeaf(&firstWindow.Panes[0])
		firstPaneDir = g.resolvePaneDir(firstLeaf)
		firstPaneCmd = buildInlineCommand(firstLeaf.Command)
	}

	lines = append(lines, "# Create session with first window (using detected terminal size)")
	newSessionLine := fmt.Sprintf(
		`tmux new-session -d -s "%s" -n "%s" -c "%s" -x "$TERM_COLS" -y "$TERM_LINES"`,
		session.SessionName, firstWindow.Name, firstPaneDir,
	)
	if firstPaneCmd != "" {
		newSessionLine += " " + firstPaneCmd
	}
	lines = append(lines, newSessionLine)
	lines = append(lines, "")

	// First window pane titles and splits
	lines = append(lines, fmt.Sprintf("# Window 1: %s", firstWindow.Name))
	result := g.generateWindowPanes(firstWindow, session.SessionName)
	lines = append(lines, result.splitLines...)
	lines = append(lines, g.generatePaneCommands(result.leafMappings, session.SessionName, firstWindow.Name)...)
	lines = append(lines, "")

	// Additional windows
	for i := 1; i < len(session.Windows); i++ {
		window := &session.Windows[i]

		winPaneDir := "$WORKING_DIR"
		winPaneCmd := ""
		if len(window.Panes) > 0 {
			firstLeaf := getFirstLeaf(&window.Panes[0])
			winPaneDir = g.resolvePaneDir(firstLeaf)
			winPaneCmd = buildInlineCommand(firstLeaf.Command)
		}

		lines = append(lines, fmt.Sprintf("# Window %d: %s", i+1, window.Name))
		newWindowLine := fmt.Sprintf(
			`tmux new-window -t "%s" -n "%s" -c "%s"`,
			session.SessionName, window.Name, winPaneDir,
		)
		if winPaneCmd != "" {
			newWindowLine += " " + winPaneCmd
		}
		lines = append(lines, newWindowLine)
		result := g.generateWindowPanes(window, session.SessionName)
		lines = append(lines, result.splitLines...)
		lines = append(lines, g.generatePaneCommands(result.leafMappings, session.SessionName, window.Name)...)
		lines = append(lines, "")
	}

	// Select default window and first pane
	defaultWindow := firstWindow
	for i := range session.Windows {
		if session.Windows[i].ID == session.DefaultWindowID {
			defaultWindow = &session.Windows[i]
			break
		}
	}

	lines = append(lines, "# Select default window")
	lines = append(lines, fmt.Sprintf(`tmux select-window -t "%s:%s"`, session.SessionName, defaultWindow.Name))
	lines = append(lines, fmt.Sprintf(`tmux select-pane -t "%s:%s.$PANE_BASE"`, session.SessionName, defaultWindow.Name))
	lines = append(lines, "")

	// Attach to session
	lines = append(lines, "# Attach to session")
	lines = append(lines, fmt.Sprintf(`tmux attach-session -t "%s"`, session.SessionName))

	// Post-commands
	if len(session.PostCommands) > 0 {
		lines = append(lines, "")
		lines = append(lines, "# Post-session commands")
		lines = append(lines, session.PostCommands...)
	}

	return strings.Join(lines, "\n"), nil
}

func (g *TmuxGenerator) generateWindowPanes(window *domain.Window, sessionName string) windowPanesResult {
	var lines []string
	var leafMappings []paneMapping
	windowTarget := fmt.Sprintf("%s:%s", sessionName, window.Name)

	if len(window.Panes) == 0 {
		return windowPanesResult{splitLines: lines, leafMappings: leafMappings}
	}

	rootPane := &window.Panes[0]

	// Step 1: Assign visual positions to all leaf panes
	leafPositions := make(map[string]int)
	positionCounter := 0

	var assignVisualPositions func(pane *domain.Pane)
	assignVisualPositions = func(pane *domain.Pane) {
		if len(pane.Children) == 0 {
			leafPositions[pane.ID] = positionCounter
			positionCounter++
			return
		}
		for i := range pane.Children {
			assignVisualPositions(&pane.Children[i])
		}
	}
	assignVisualPositions(rootPane)

	// Step 2: Track created positions
	createdPositions := make(map[int]bool)
	createdPositions[0] = true

	// Helper: Get first leaf position in subtree
	var getFirstLeafPosition func(pane *domain.Pane) int
	getFirstLeafPosition = func(pane *domain.Pane) int {
		if len(pane.Children) == 0 {
			return leafPositions[pane.ID]
		}
		return getFirstLeafPosition(&pane.Children[0])
	}

	// Helper: Calculate current tmux index
	getCurrentIndex := func(visualPos int) string {
		count := 0
		for i := 0; i < visualPos; i++ {
			if createdPositions[i] {
				count++
			}
		}
		if count == 0 {
			return fmt.Sprintf("%s.$PANE_BASE", windowTarget)
		}
		return fmt.Sprintf("%s.$((PANE_BASE+%d))", windowTarget, count)
	}

	// Step 3: Generate splits
	var processPane func(pane *domain.Pane, parentDirection domain.Direction)
	processPane = func(pane *domain.Pane, parentDirection domain.Direction) {
		if len(pane.Children) == 0 {
			visualPos := leafPositions[pane.ID]
			leafMappings = append(leafMappings, paneMapping{pane: pane, paneOffset: visualPos})
			return
		}

		direction := pane.Direction
		if direction == "" {
			direction = parentDirection
		}

		splitFlag := "-v"
		if direction == domain.DirectionHorizontal {
			splitFlag = "-h"
		}

		// Calculate cumulative sizes
		sizes := make([]float64, len(pane.Children))
		for i, child := range pane.Children {
			sizes[i] = child.Size
		}

		cumulative := make([]float64, len(sizes))
		cumulative[len(sizes)-1] = sizes[len(sizes)-1]
		for i := len(sizes) - 2; i >= 0; i-- {
			cumulative[i] = cumulative[i+1] + sizes[i]
		}

		// Create splits
		for i := 1; i < len(pane.Children); i++ {
			childFirstLeafPos := getFirstLeafPosition(&pane.Children[i])
			prevChildFirstLeafPos := getFirstLeafPosition(&pane.Children[i-1])
			splitTarget := getCurrentIndex(prevChildFirstLeafPos)

			remainingSize := cumulative[i]
			currentPaneSize := cumulative[i-1]
			percentage := int((remainingSize / currentPaneSize) * 100)

			childFirstLeaf := getFirstLeaf(&pane.Children[i])
			paneDir := g.resolvePaneDir(childFirstLeaf)
			inlineCmd := buildInlineCommand(childFirstLeaf.Command)

			splitLine := fmt.Sprintf(
				`tmux split-window %s -l %d%% -t "%s" -c "%s"`,
				splitFlag, percentage, splitTarget, paneDir,
			)
			if inlineCmd != "" {
				splitLine += " " + inlineCmd
			}
			lines = append(lines, splitLine)

			createdPositions[childFirstLeafPos] = true
		}

		// Recurse into children
		for i := range pane.Children {
			processPane(&pane.Children[i], direction)
		}
	}

	processPane(rootPane, window.RootDirection)

	return windowPanesResult{splitLines: lines, leafMappings: leafMappings}
}

func (g *TmuxGenerator) generatePaneCommands(leafMappings []paneMapping, sessionName, windowName string) []string {
	var lines []string
	windowTarget := fmt.Sprintf("%s:%s", sessionName, windowName)

	for _, mapping := range leafMappings {
		pane := mapping.pane
		paneOffset := mapping.paneOffset

		var paneTarget string
		if paneOffset == 0 {
			paneTarget = fmt.Sprintf("%s.$PANE_BASE", windowTarget)
		} else {
			paneTarget = fmt.Sprintf("%s.$((PANE_BASE+%d))", windowTarget, paneOffset)
		}

		if pane.Name != "" {
			lines = append(lines, fmt.Sprintf(`tmux select-pane -t "%s" -T "%s"`, paneTarget, pane.Name))
		}
	}

	return lines
}

func isAbsolutePath(path string) bool {
	return strings.HasPrefix(path, "/") ||
		strings.HasPrefix(path, "~") ||
		strings.HasPrefix(path, "$")
}
