package generator

import (
	"fmt"
	"math"
	"strings"

	"github.com/ajmasia/shellify/internal/domain"
)

// ZellijGenerator generates KDL layout files for zellij sessions.
type ZellijGenerator struct{}

func (g *ZellijGenerator) Name() string {
	return "zellij"
}

func (g *ZellijGenerator) FileExtension() string {
	return ".kdl"
}

func (g *ZellijGenerator) Generate(session domain.Session) (string, error) {
	lines := []string{
		fmt.Sprintf("// Session: %s", session.SessionName),
		"// Generated by Shellify",
		"",
		"layout {",
	}

	// Default tab template with tab-bar and status-bar
	lines = append(lines,
		"    default_tab_template {",
		"        pane size=1 borderless=true {",
		`            plugin location="zellij:tab-bar"`,
		"        }",
		"        children",
		"        pane size=2 borderless=true {",
		`            plugin location="zellij:status-bar"`,
		"        }",
		"    }",
		"",
	)

	// Session working directory
	if session.WorkingDirectory != "" {
		lines = append(lines, fmt.Sprintf(`    cwd "%s"`, session.WorkingDirectory))
		lines = append(lines, "")
	}

	// Determine focused window
	focusedWindowID := ""
	if session.DefaultWindowID != "" {
		focusedWindowID = session.DefaultWindowID
	} else if len(session.Windows) > 0 {
		focusedWindowID = session.Windows[0].ID
	}

	// Generate tabs (windows)
	for i := range session.Windows {
		window := &session.Windows[i]
		isFocused := window.ID == focusedWindowID
		lines = append(lines, g.generateTab(window, isFocused, 1)...)
		lines = append(lines, "")
	}

	lines = append(lines, "}")

	return strings.Join(lines, "\n"), nil
}

func (g *ZellijGenerator) generateTab(window *domain.Window, isFocused bool, level int) []string {
	var lines []string
	ind := indent(level)

	// Build tab attributes
	attrs := []string{fmt.Sprintf(`name="%s"`, window.Name)}
	if isFocused {
		attrs = append(attrs, "focus=true")
	}

	lines = append(lines, fmt.Sprintf("%stab %s {", ind, strings.Join(attrs, " ")))

	// Generate panes
	if len(window.Panes) == 0 {
		lines = append(lines, fmt.Sprintf("%s    pane", ind))
	} else if len(window.Panes) == 1 {
		rootPane := &window.Panes[0]
		if isLeafPane(rootPane) {
			lines = append(lines, g.generateLeafPane(rootPane, level+1, 0)...)
		} else {
			lines = append(lines, g.generatePane(rootPane, window.RootDirection, level+1)...)
		}
	} else {
		for i := range window.Panes {
			lines = append(lines, g.generatePane(&window.Panes[i], window.RootDirection, level+1)...)
		}
	}

	lines = append(lines, fmt.Sprintf("%s}", ind))

	return lines
}

type flattenedPane struct {
	pane       *domain.Pane
	scaledSize float64
}

func (g *ZellijGenerator) generatePane(pane *domain.Pane, parentDirection domain.Direction, level int) []string {
	if isLeafPane(pane) {
		return g.generateLeafPane(pane, level, 0)
	}

	var lines []string
	ind := indent(level)
	direction := pane.Direction
	if direction == "" {
		direction = parentDirection
	}
	zellijDirection := toZellijDirection(direction)

	// Collect and flatten leaves
	flattenedChildren := g.collectLeafPanes(pane, direction, 100)

	lines = append(lines, fmt.Sprintf(`%spane split_direction="%s" {`, ind, zellijDirection))

	for _, fp := range flattenedChildren {
		if isLeafPane(fp.pane) {
			lines = append(lines, g.generateLeafPane(fp.pane, level+1, fp.scaledSize)...)
		} else {
			lines = append(lines, g.generatePane(fp.pane, direction, level+1)...)
		}
	}

	lines = append(lines, fmt.Sprintf("%s}", ind))

	return lines
}

func (g *ZellijGenerator) generateLeafPane(pane *domain.Pane, level int, sizeOverride float64) []string {
	var lines []string
	ind := indent(level)

	// Build pane attributes
	var attrs []string
	size := sizeOverride
	if size == 0 {
		size = pane.Size
	}
	if size > 0 && size != 100 {
		attrs = append(attrs, fmt.Sprintf(`size="%d%%"`, int(math.Round(size))))
	}

	attrStr := ""
	if len(attrs) > 0 {
		attrStr = " " + strings.Join(attrs, " ")
	}

	// Check if pane has content
	hasContent := pane.Name != "" || pane.WorkingDirectory != "" || pane.Command != ""

	if !hasContent {
		lines = append(lines, fmt.Sprintf("%spane%s", ind, attrStr))
	} else {
		lines = append(lines, fmt.Sprintf("%spane%s {", ind, attrStr))

		if pane.Name != "" {
			lines = append(lines, fmt.Sprintf(`%s    name "%s"`, ind, pane.Name))
		}

		if pane.WorkingDirectory != "" {
			lines = append(lines, fmt.Sprintf(`%s    cwd "%s"`, ind, pane.WorkingDirectory))
		}

		if pane.Command != "" {
			parts := strings.Fields(pane.Command)
			program := parts[0]
			args := parts[1:]

			lines = append(lines, fmt.Sprintf(`%s    command "%s"`, ind, program))
			if len(args) > 0 {
				quotedArgs := make([]string, len(args))
				for i, arg := range args {
					quotedArgs[i] = fmt.Sprintf(`"%s"`, arg)
				}
				lines = append(lines, fmt.Sprintf(`%s    args %s`, ind, strings.Join(quotedArgs, " ")))
			}
		}

		lines = append(lines, fmt.Sprintf("%s}", ind))
	}

	return lines
}

func (g *ZellijGenerator) collectLeafPanes(pane *domain.Pane, direction domain.Direction, scale float64) []flattenedPane {
	if isLeafPane(pane) {
		return []flattenedPane{{pane: pane, scaledSize: (pane.Size * scale) / 100}}
	}

	paneDirection := pane.Direction
	if paneDirection == "" {
		paneDirection = direction
	}

	var children []flattenedPane

	for i := range pane.Children {
		child := &pane.Children[i]
		if isLeafPane(child) {
			children = append(children, flattenedPane{
				pane:       child,
				scaledSize: (child.Size * scale) / 100,
			})
		} else {
			childDirection := child.Direction
			if childDirection == "" {
				childDirection = paneDirection
			}
			if childDirection == paneDirection {
				// Same direction - flatten
				childScale := (child.Size * scale) / 100
				children = append(children, g.collectLeafPanes(child, paneDirection, childScale)...)
			} else {
				// Different direction - keep as container
				children = append(children, flattenedPane{
					pane:       child,
					scaledSize: (child.Size * scale) / 100,
				})
			}
		}
	}

	return children
}

// Helper functions

func indent(level int) string {
	return strings.Repeat("    ", level)
}

func isLeafPane(pane *domain.Pane) bool {
	return len(pane.Children) == 0
}

// toZellijDirection converts our internal direction to Zellij's split_direction.
// In our model: "horizontal" means panes side by side (left|right)
// In Zellij: "horizontal" means horizontal split line (panes stacked top/bottom)
// So we swap them.
func toZellijDirection(direction domain.Direction) string {
	if direction == domain.DirectionHorizontal {
		return "vertical"
	}
	return "horizontal"
}
