package generator

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/ajmasia/shellify/internal/domain"
)

func TestZellijGenerator_Generate(t *testing.T) {
	gen := &ZellijGenerator{}

	t.Run("generates layout for simple session", func(t *testing.T) {
		session := createSimpleSession()
		session.TargetMultiplexer = domain.MultiplexerZellij
		output, err := gen.Generate(session)
		require.NoError(t, err)

		// Verify layout header
		assert.Contains(t, output, "// Session: proj_dev")
		assert.Contains(t, output, "// Generated by Shellify")

		// Verify layout structure
		assert.Contains(t, output, "layout {")

		// Verify default tab template
		assert.Contains(t, output, "default_tab_template {")
		assert.Contains(t, output, `plugin location="zellij:tab-bar"`)
		assert.Contains(t, output, `plugin location="zellij:status-bar"`)

		// Verify working directory
		assert.Contains(t, output, `cwd "~/projects"`)

		// Verify tab with focus
		assert.Contains(t, output, `tab name="editor" focus=true`)

		// Verify pane with command
		assert.Contains(t, output, `command "nvim"`)
		assert.Contains(t, output, `args "."`)
	})

	t.Run("generates layout with multiple panes", func(t *testing.T) {
		session := createMultiPaneSession()
		session.TargetMultiplexer = domain.MultiplexerZellij
		output, err := gen.Generate(session)
		require.NoError(t, err)

		// Verify split direction (our horizontal -> zellij vertical)
		assert.Contains(t, output, `split_direction="vertical"`)

		// Verify pane sizes
		assert.Contains(t, output, `size="60%"`)
		assert.Contains(t, output, `size="40%"`)

		// Verify pane names
		assert.Contains(t, output, `name "editor"`)
		assert.Contains(t, output, `name "terminal"`)
	})

	t.Run("generates layout with multiple windows", func(t *testing.T) {
		session := createMultiWindowSession()
		session.TargetMultiplexer = domain.MultiplexerZellij
		output, err := gen.Generate(session)
		require.NoError(t, err)

		// Verify multiple tabs
		assert.Contains(t, output, `tab name="code"`)
		assert.Contains(t, output, `tab name="server"`)

		// First tab should have focus (default window)
		assert.Contains(t, output, `tab name="code" focus=true`)
	})

	t.Run("handles empty working directory", func(t *testing.T) {
		session := createSimpleSession()
		session.WorkingDirectory = ""
		output, err := gen.Generate(session)
		require.NoError(t, err)

		// Should not have cwd line
		assert.NotContains(t, output, "cwd")
	})

	t.Run("handles pane working directory", func(t *testing.T) {
		session := createSimpleSession()
		session.Windows[0].Panes[0].WorkingDirectory = "src/components"
		output, err := gen.Generate(session)
		require.NoError(t, err)

		assert.Contains(t, output, `cwd "src/components"`)
	})

	t.Run("handles window with no panes", func(t *testing.T) {
		session := domain.Session{
			SessionName: "empty",
			Windows: []domain.Window{
				{
					ID:   "w1",
					Name: "empty",
				},
			},
			DefaultWindowID: "w1",
		}
		output, err := gen.Generate(session)
		require.NoError(t, err)

		// Should have a default pane
		assert.Contains(t, output, "pane")
	})

	t.Run("handles pane without command", func(t *testing.T) {
		session := createSimpleSession()
		session.Windows[0].Panes[0].Command = ""
		session.Windows[0].Panes[0].Name = ""
		output, err := gen.Generate(session)
		require.NoError(t, err)

		// Should have pane without command block
		lines := strings.Split(output, "\n")
		foundSimplPane := false
		for _, line := range lines {
			trimmed := strings.TrimSpace(line)
			if trimmed == "pane" {
				foundSimplPane = true
				break
			}
		}
		assert.True(t, foundSimplPane, "expected simple pane declaration")
	})

	t.Run("focuses correct default window", func(t *testing.T) {
		session := createMultiWindowSession()
		session.DefaultWindowID = "w2" // Second window (server)
		output, err := gen.Generate(session)
		require.NoError(t, err)

		// Server tab should have focus
		assert.Contains(t, output, `tab name="server" focus=true`)
		// Code tab should not have focus
		assert.NotContains(t, output, `tab name="code" focus=true`)
	})
}

func TestZellijGenerator_Name(t *testing.T) {
	gen := &ZellijGenerator{}
	assert.Equal(t, "zellij", gen.Name())
}

func TestZellijGenerator_FileExtension(t *testing.T) {
	gen := &ZellijGenerator{}
	assert.Equal(t, ".kdl", gen.FileExtension())
}

func TestToZellijDirection(t *testing.T) {
	tests := []struct {
		input    domain.Direction
		expected string
	}{
		{domain.DirectionHorizontal, "vertical"},
		{domain.DirectionVertical, "horizontal"},
	}

	for _, tt := range tests {
		t.Run(string(tt.input), func(t *testing.T) {
			result := toZellijDirection(tt.input)
			assert.Equal(t, tt.expected, result)
		})
	}
}

func TestZellijGenerator_OutputIsValidKDL(t *testing.T) {
	gen := &ZellijGenerator{}
	session := createMultiWindowSession()
	output, err := gen.Generate(session)
	require.NoError(t, err)

	// Basic validation that output looks like valid KDL
	lines := strings.Split(output, "\n")

	// First non-comment line should open layout block
	assert.Contains(t, output, "layout {")

	// Should have matching braces
	openBraces := strings.Count(output, "{")
	closeBraces := strings.Count(output, "}")
	assert.Equal(t, openBraces, closeBraces, "unbalanced braces in output")

	// Should not have any unclosed quotes
	quoteCount := strings.Count(output, `"`)
	assert.Equal(t, 0, quoteCount%2, "unbalanced quotes in output")

	// First line should be a comment
	assert.True(t, strings.HasPrefix(lines[0], "//"), "first line should be a comment")
}

func TestZellijGenerator_NestedPanes(t *testing.T) {
	gen := &ZellijGenerator{}

	// Create a session with nested panes (vertical split containing horizontal splits)
	session := domain.Session{
		ID:                "session-nested",
		Name:              "nested",
		SessionName:       "proj_nested",
		WorkingDirectory:  "~/app",
		TargetMultiplexer: domain.MultiplexerZellij,
		DefaultWindowID:   "w1",
		Windows: []domain.Window{
			{
				ID:            "w1",
				Name:          "dev",
				RootDirection: domain.DirectionVertical,
				Panes: []domain.Pane{
					{
						ID:        "root",
						Size:      100,
						Direction: domain.DirectionVertical,
						Children: []domain.Pane{
							{
								ID:        "top",
								Size:      60,
								Direction: domain.DirectionHorizontal,
								Children: []domain.Pane{
									{ID: "p1", Name: "editor", Command: "nvim .", Size: 70},
									{ID: "p2", Name: "files", Command: "lf", Size: 30},
								},
							},
							{
								ID:      "p3",
								Name:    "terminal",
								Command: "",
								Size:    40,
							},
						},
					},
				},
			},
		},
	}

	output, err := gen.Generate(session)
	require.NoError(t, err)

	// Should contain nested split directions
	assert.Contains(t, output, `split_direction=`)

	// Should contain all pane names
	assert.Contains(t, output, `name "editor"`)
	assert.Contains(t, output, `name "files"`)
	assert.Contains(t, output, `name "terminal"`)
}
